# Generated by Django 3.2.7 on 2023-04-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('COLD', 'COLD'), ('DEAD', 'DEAD'), ('POTENTIAL', 'POTENTIAL'), ('CONVERTED', 'CONVERTED')], max_length=200, null=True),
        ),
    ]
