# Generated by Django 3.2.7 on 2023-04-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='payment_status',
            field=models.CharField(choices=[('RECIEVED', 'RECIEVED'), ('LEFT', 'LEFT')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='total_payment',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
